package com.github.pcbouman_eur.testing.cli;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

public final class ClassUtils {

    private ClassUtils() {}

    protected static void initClassloader() {
        try {
            Thread currentThread = Thread.currentThread();
            ClassLoader currentCL = currentThread.getContextClassLoader();
            File cwd = new File(System.getProperty("user.dir"));
            URL[] cp = {cwd.toURI().toURL()};
            URLClassLoader urlcl = URLClassLoader.newInstance(cp, currentCL);
            currentThread.setContextClassLoader(urlcl);
        }
        catch (MalformedURLException ex) {
            throw new AssertionError("Unexpected error. URL generated by a File object was malformed", ex);
        }
    }

    protected static Class<?> loadClass(String className) {
        try {
            return Thread.currentThread().getContextClassLoader().loadClass(className);
        }
        catch (ClassNotFoundException cnf) {
            throw new IllegalArgumentException("Class with name "+className+" was not found.");
        }
//        try {
//            return ClassLoader.getSystemClassLoader().loadClass(className);
//        }
//        catch (ClassNotFoundException ignored) {
//            // This ignored because we will make another attempt
//        }
//        try {
//            File cwd = new File(System.getProperty("user.dir"));
//            URL [] cp = {cwd.toURI().toURL()};
//            URLClassLoader urlcl = new URLClassLoader(cp);
//            return urlcl.loadClass(className);
//        }
//        catch (ClassNotFoundException cnf) {
//            throw new IllegalArgumentException("Class with name "+className+" was not found.");
//        }
//        catch (SecurityException ex) {
//            throw new AssertionError("Unexpected error. " +
//                    "Unable to load classes from the current working directory.", ex);
//        }
//        catch (MalformedURLException ex) {
//            throw new AssertionError("Unexpected error. URL generated by a File class was malformed", ex);
//        }
    }

}
