/* Copyright 2025 Paul Bouman

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package com.github.pcbouman_eur.testing.cli.util;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;

/**
 * Helper class to ensure Test related and student classes are loaded. Not sure if this is still really necessary
 * since we now handle many things in wrapper scripts and during installation to ensure which classes are on the
 * classpath.
 */
public final class ClassUtils {

    private ClassUtils() {}

    public static void initClassloader() {
        try {
            Thread currentThread = Thread.currentThread();
            ClassLoader currentCL = currentThread.getContextClassLoader();
            File cwd = new File(System.getProperty("user.dir"));
            URL[] cp = {cwd.toURI().toURL()};
            URLClassLoader urlcl = URLClassLoader.newInstance(cp, currentCL);
            currentThread.setContextClassLoader(urlcl);
        }
        catch (MalformedURLException ex) {
            throw new AssertionError("Unexpected error. URL generated by a File object was malformed", ex);
        }
    }

    public static Class<?> loadClass(String className) {
        try {
            return Thread.currentThread().getContextClassLoader().loadClass(className);
        }
        catch (ClassNotFoundException cnf) {
            throw new IllegalArgumentException("Class with name "+className+" was not found.");
        }
//        try {
//            return ClassLoader.getSystemClassLoader().loadClass(className);
//        }
//        catch (ClassNotFoundException ignored) {
//            // This ignored because we will make another attempt
//        }
//        try {
//            File cwd = new File(System.getProperty("user.dir"));
//            URL [] cp = {cwd.toURI().toURL()};
//            URLClassLoader urlcl = new URLClassLoader(cp);
//            return urlcl.loadClass(className);
//        }
//        catch (ClassNotFoundException cnf) {
//            throw new IllegalArgumentException("Class with name "+className+" was not found.");
//        }
//        catch (SecurityException ex) {
//            throw new AssertionError("Unexpected error. " +
//                    "Unable to load classes from the current working directory.", ex);
//        }
//        catch (MalformedURLException ex) {
//            throw new AssertionError("Unexpected error. URL generated by a File class was malformed", ex);
//        }
    }

}
